"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, CircleDollarSign, Loader2, Search, UserRound, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { useAdminIdentity } from "@/components/admin/admin-gate";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { adminClient } from "@/lib/admin-client";
import type { AdminApproval, AdminWalletSearchItem, WalletAdjustmentInput } from "@/types/admin";

function approvalPayload(approval: AdminApproval): WalletAdjustmentInput | null {
  const payload = approval.payload as Partial<WalletAdjustmentInput>;
  if (!payload.user_id || !payload.direction || !payload.amount || !payload.reason || !payload.ticket_reference) return null;
  return { user_id: payload.user_id, direction: payload.direction, amount: payload.amount, reason: payload.reason, ticket_reference: payload.ticket_reference, approval_id: approval.id };
}

export function BalanceAdjustmentPanel() {
  const identity = useAdminIdentity();
  const queryClient = useQueryClient();
  const [search, setSearch] = useState(""); const [debounced, setDebounced] = useState(""); const [selected, setSelected] = useState<AdminWalletSearchItem | null>(null);
  const canAdjust = identity.role === "super_admin" || identity.role === "finance_operator";
  useEffect(() => { const timer = window.setTimeout(() => setDebounced(search.trim()), 300); return () => window.clearTimeout(timer); }, [search]);
  const wallets = useQuery({ queryKey: ["admin", "wallets", debounced], queryFn: () => adminClient.wallets(`?page=1&limit=20&search=${encodeURIComponent(debounced)}`) });
  const approvals = useQuery({ queryKey: ["admin", "approvals", "wallet"], queryFn: () => adminClient.approvalsPaged("?page=1&limit=100"), refetchInterval: 8000 });
  const walletApprovals = useMemo(() => (approvals.data?.data || []).filter((item) => item.action_type === "wallet.adjust"), [approvals.data]);
  async function refresh() { await Promise.all([queryClient.invalidateQueries({ queryKey: ["admin", "wallets"] }), queryClient.invalidateQueries({ queryKey: ["admin", "approvals"] })]); }
  const adjust = useMutation({ mutationFn: adminClient.adjustWallet, onSuccess: async (result) => { if (result.status === "pending_approval") toast.success("Balance adjustment submitted for approval"); else { toast.success("User balance updated"); if (result.wallet && selected) setSelected({ ...selected, balance: result.wallet.balance, version: result.wallet.version }); } await refresh(); }, onError: (reason) => toast.error(reason instanceof Error ? reason.message : "Balance adjustment failed") });
  const decide = useMutation({ mutationFn: ({ approval, decision }: { approval: AdminApproval; decision: "approve" | "reject" }) => decision === "approve" ? adminClient.approve(approval.id, "Reviewed from balance adjustment") : adminClient.reject(approval.id, "Rejected from balance adjustment"), onSuccess: async (_data, variables) => { toast.success(`Adjustment request ${variables.decision}d`); await refresh(); }, onError: (reason) => toast.error(reason instanceof Error ? reason.message : "Approval action failed") });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const data = new FormData(event.currentTarget); adjust.mutate({ user_id: selected.user_id, direction: String(data.get("direction")) as "credit" | "debit", amount: String(data.get("amount")), ticket_reference: String(data.get("ticket_reference")), reason: String(data.get("reason")) }); }

  return <div className="space-y-6"><div><p className="text-sm font-medium text-slate-500">Wallet administration</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Adjust User Balance</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Search an existing player wallet, review its current balance, then credit or debit coins with an auditable reason.</p></div>
    {!canAdjust && <Alert variant="warning"><AlertTitle>Read-only access</AlertTitle><AlertDescription>Your administrator role cannot create wallet adjustments.</AlertDescription></Alert>}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.15fr)_minmax(380px,.85fr)]"><Card><CardHeader><CardTitle>Find a user</CardTitle><CardDescription>Search uses the platform user ID stored on each game wallet.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="relative"><Search className="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-slate-400" /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search user ID…" /></div>{wallets.isLoading ? <div className="grid min-h-40 place-items-center"><Loader2 className="animate-spin text-slate-400" /></div> : wallets.data?.data.length ? <Table><TableHeader><TableRow><TableHead>User ID</TableHead><TableHead>Balance</TableHead><TableHead>Updated</TableHead><TableHead /></TableRow></TableHeader><TableBody>{wallets.data.data.map((wallet) => <TableRow key={wallet.id} className={selected?.id === wallet.id ? "bg-slate-100" : ""}><TableCell className="font-medium">{wallet.user_id}</TableCell><TableCell>{wallet.balance} {wallet.currency.code}</TableCell><TableCell className="text-slate-500">{new Date(wallet.updated_at).toLocaleString()}</TableCell><TableCell className="text-right"><Button size="sm" variant={selected?.id === wallet.id ? "default" : "outline"} onClick={() => setSelected(wallet)}>{selected?.id === wallet.id ? <Check /> : <UserRound />} Select</Button></TableCell></TableRow>)}</TableBody></Table> : <div className="rounded-lg border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No player wallet matches this search.</div>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Balance adjustment</CardTitle><CardDescription>{selected ? `Selected ${selected.user_id}` : "Select a user wallet before continuing."}</CardDescription></CardHeader><CardContent>{selected ? <form className="space-y-4" onSubmit={submit}><div className="rounded-xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2 text-sm text-slate-300"><WalletCards className="size-4" /> Current balance</div><p className="mt-2 text-3xl font-bold">{selected.balance} <span className="text-base text-slate-400">{selected.currency.code}</span></p><p className="mt-1 text-xs text-slate-400">Wallet version {selected.version}</p></div><div className="space-y-2"><Label>Direction</Label><Select name="direction" defaultValue="credit"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="credit">Credit balance</SelectItem><SelectItem value="debit">Debit balance</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label htmlFor="amount">Amount</Label><Input id="amount" name="amount" inputMode="numeric" pattern="[1-9][0-9]*" required /></div><div className="space-y-2"><Label htmlFor="ticket_reference">Ticket reference</Label><Input id="ticket_reference" name="ticket_reference" minLength={3} maxLength={128} placeholder="SUPPORT-1234" required /></div><div className="space-y-2"><Label htmlFor="reason">Reason</Label><Textarea id="reason" name="reason" minLength={3} maxLength={250} placeholder="Explain why this adjustment is required" required /></div><Button className="w-full" size="lg" disabled={!canAdjust || adjust.isPending}>{adjust.isPending ? <Loader2 className="animate-spin" /> : <CircleDollarSign />} {adjust.isPending ? "Updating…" : "Update balance"}</Button></form> : <div className="grid min-h-80 place-items-center rounded-xl border border-dashed border-slate-300 text-center"><div><UserRound className="mx-auto size-8 text-slate-400" /><p className="mt-3 text-sm font-medium">No user selected</p><p className="mt-1 text-xs text-slate-500">Choose a wallet from the search results.</p></div></div>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Balance adjustment approvals</CardTitle><CardDescription>Large adjustments follow the existing dual-control policy. Another eligible admin approves; the requester then applies the exact approved payload.</CardDescription></CardHeader><CardContent>{walletApprovals.length ? <Table><TableHeader><TableRow><TableHead>User</TableHead><TableHead>Adjustment</TableHead><TableHead>Status</TableHead><TableHead>Requester</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{walletApprovals.map((approval) => { const payload = approval.payload as Partial<WalletAdjustmentInput>; const requestedByMe = approval.requested_by_admin_id === identity.id; const readyPayload = approvalPayload(approval); return <TableRow key={approval.id}><TableCell className="font-medium">{payload.user_id || "Unknown"}</TableCell><TableCell className="capitalize">{payload.direction} {payload.amount}</TableCell><TableCell><Badge variant={approval.status === "approved" ? "success" : approval.status === "pending" ? "warning" : "secondary"}>{approval.status}</Badge></TableCell><TableCell>{requestedByMe ? "You" : "Another admin"}</TableCell><TableCell><div className="flex justify-end gap-2">{approval.status === "pending" && !requestedByMe && <><Button size="sm" variant="outline" onClick={() => decide.mutate({ approval, decision: "reject" })}>Reject</Button><Button size="sm" onClick={() => decide.mutate({ approval, decision: "approve" })}>Approve</Button></>}{approval.status === "approved" && requestedByMe && readyPayload && <Button size="sm" disabled={adjust.isPending} onClick={() => adjust.mutate(readyPayload)}>Apply adjustment</Button>}{approval.status === "pending" && requestedByMe && <span className="text-xs text-slate-500">Waiting for another admin</span>}</div></TableCell></TableRow>; })}</TableBody></Table> : <p className="text-sm text-slate-500">No wallet adjustment approvals are visible to this account.</p>}</CardContent></Card>
  </div>;
}
