"use client";

import { useState } from "react";
import { useFieldArray, useForm, useWatch } from "react-hook-form";
import { useQuery } from "@tanstack/react-query";
import { CheckCircle2, ImagePlus, Info, Loader2, Plus, Save, Trash2, Upload } from "lucide-react";
import { adminClient } from "@/lib/admin-client";
import type { AdminAsset, CreateAdminConfigInput } from "@/types/admin";
import type { ConfigValidationPreview } from "@/lib/admin-config-validation";

export const newConfigDefaults: CreateAdminConfigInput = {
  betting_duration_ms: 10000, lock_duration_ms: 1000, drawing_duration_ms: 3000, result_duration_ms: 4000,
  min_bet: "10", max_single_bet: "10000", max_round_bet: "50000", notes: "",
  options: ["FALCON", "TIGER", "PANDA", "LION", "SHARK", "DRAGON", "CROWN", "DIAMOND"].map((code, index) => ({ code, name: code[0] + code.slice(1).toLowerCase(), image_url: null, asset_id: null, display_order: index + 1, payout_numerator: "4", payout_denominator: "1", probability_weight: "1", is_enabled: true })),
  chip_values: [10, 50, 100, 500].map((amount, index) => ({ amount: String(amount), display_order: index + 1, is_enabled: true })),
};

export function ConfigEditor({ initial, submitLabel, onSave }: { initial: CreateAdminConfigInput; submitLabel: string; onSave: (payload: CreateAdminConfigInput) => Promise<void> }) {
  const { register, control, setValue, handleSubmit, formState: { isSubmitting } } = useForm<CreateAdminConfigInput>({ defaultValues: initial });
  const optionFields = useFieldArray({ control, name: "options" }); const chipFields = useFieldArray({ control, name: "chip_values" });
  const values = useWatch({ control }) as CreateAdminConfigInput;
  const assets = useQuery({ queryKey: ["admin", "assets"], queryFn: adminClient.assets, staleTime: 20_000 });
  const [preview, setPreview] = useState<ConfigValidationPreview | null>(null); const [error, setError] = useState(""); const [uploading, setUploading] = useState<number | null>(null); const [assetTarget, setAssetTarget] = useState<number | null>(null);
  async function validate(payload: CreateAdminConfigInput) { const next = await adminClient.validateConfig(payload); setPreview(next); return next; }
  async function submit(payload: CreateAdminConfigInput) { setError(""); try { const result = await validate(payload); if (!result.valid) { setError("Resolve the validation failures before saving this draft."); return; } await onSave(payload); } catch (reason) { setError(reason instanceof Error ? reason.message : "Configuration could not be saved"); } }
  async function upload(index: number, file: File | undefined) { if (!file) return; setUploading(index); setError(""); try { const asset = await adminClient.uploadAsset(file); setValue(`options.${index}.asset_id`, asset.id, { shouldDirty: true }); setValue(`options.${index}.image_url`, asset.cdn_url, { shouldDirty: true }); await assets.refetch(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Artwork upload failed"); } finally { setUploading(null); } }
  function selectAsset(index: number, asset: AdminAsset) { setValue(`options.${index}.asset_id`, asset.id, { shouldDirty: true }); setValue(`options.${index}.image_url`, asset.cdn_url, { shouldDirty: true }); setAssetTarget(null); }
  return <form onSubmit={handleSubmit(submit)} className="admin-config-editor">
    {error && <div className="admin-form-error" role="alert">{error}</div>}
    <section className="admin-form-section"><div className="admin-form-section__heading"><div><span className="admin-eyebrow">01 · Timing and limits</span><h2>Round guardrails</h2><p>Durations use milliseconds; coin limits remain lossless integer strings.</p></div></div><div className="admin-form-grid admin-form-grid--4">{(["betting_duration_ms", "lock_duration_ms", "drawing_duration_ms", "result_duration_ms"] as const).map((name) => <label key={name}>{name.replaceAll("_", " ")}<input type="number" {...register(name, { valueAsNumber: true })} /></label>)}</div><div className="admin-form-grid admin-form-grid--3 admin-form-gap">{(["min_bet", "max_single_bet", "max_round_bet"] as const).map((name) => <label key={name}>{name.replaceAll("_", " ")}<input inputMode="numeric" {...register(name)} /></label>)}</div><label className="admin-form-full">Internal notes<textarea rows={3} {...register("notes")} /></label></section>
    <section className="admin-form-section"><div className="admin-form-section__heading"><div><span className="admin-eyebrow">02 · Option matrix</span><h2>Eight outcomes and artwork</h2><p>Artwork is selected from managed assets. Uploads must be square PNG, JPEG, or WebP, 256–2048px and at most 2MB.</p></div></div><div className="admin-option-editor-grid">{optionFields.fields.map((field, index) => <article className="admin-option-editor" key={field.id}><div className="admin-option-editor__top"><span>Option {index + 1}</span><label className="admin-switch"><input type="checkbox" {...register(`options.${index}.is_enabled`)} /><i /> Enabled</label></div><div className="admin-option-editor__preview"><div className="admin-option-card__art">{values.options?.[index]?.image_url ? <img src={values.options[index].image_url || ""} alt="" /> : <span>{values.options?.[index]?.code?.slice(0, 1) || "?"}</span>}</div><div><strong>{values.options?.[index]?.name || "Untitled"}</strong><small>{values.options?.[index]?.asset_id ? "Managed artwork linked" : "Artwork required"}</small></div></div><div className="admin-asset-actions"><label className="admin-secondary-button"><Upload />{uploading === index ? "Uploading…" : "Upload"}<input type="file" hidden accept="image/png,image/jpeg,image/webp" disabled={uploading !== null} onChange={(event) => void upload(index, event.target.files?.[0])} /></label><button type="button" className="admin-secondary-button" onClick={() => setAssetTarget(assetTarget === index ? null : index)}><ImagePlus /> Library</button></div>{assetTarget === index && <div className="admin-asset-picker">{(assets.data || []).filter((asset) => asset.status === "ready").map((asset) => <button type="button" key={asset.id} onClick={() => selectAsset(index, asset)}><span>{asset.cdn_url ? <img src={asset.cdn_url} alt="" /> : <ImagePlus />}</span><small>{asset.object_key.split("/").at(-1)}</small></button>)}{!assets.data?.length && <p>No ready assets yet.</p>}</div>}<input type="hidden" {...register(`options.${index}.asset_id`)} /><input type="hidden" {...register(`options.${index}.image_url`)} /><div className="admin-form-grid admin-form-grid--2"><label>Code<input {...register(`options.${index}.code`)} /></label><label>Name<input {...register(`options.${index}.name`)} /></label><label>Display order<input type="number" {...register(`options.${index}.display_order`, { valueAsNumber: true })} /></label><label>Probability weight<input {...register(`options.${index}.probability_weight`)} /></label><label>Payout numerator<input {...register(`options.${index}.payout_numerator`)} /></label><label>Payout denominator<input {...register(`options.${index}.payout_denominator`)} /></label></div></article>)}</div></section>
    <section className="admin-form-section"><div className="admin-form-section__heading"><div><span className="admin-eyebrow">03 · Chips</span><h2>Quick selection presets</h2></div><button type="button" className="admin-secondary-button" disabled={chipFields.fields.length >= 12} onClick={() => chipFields.append({ amount: "1000", display_order: chipFields.fields.length + 1, is_enabled: true })}><Plus /> Add chip</button></div><div className="admin-chip-editor-list">{chipFields.fields.map((field, index) => <div className="admin-chip-editor" key={field.id}><label>Amount<input {...register(`chip_values.${index}.amount`)} /></label><label>Order<input type="number" {...register(`chip_values.${index}.display_order`, { valueAsNumber: true })} /></label><label className="admin-switch"><input type="checkbox" {...register(`chip_values.${index}.is_enabled`)} /><i /> Enabled</label><button type="button" onClick={() => chipFields.remove(index)} aria-label="Remove chip"><Trash2 /></button></div>)}</div></section>
    <section className="admin-validation-panel"><div className="admin-panel__top"><div><span className="admin-eyebrow">Validation preview</span><h2>Probability and theoretical return</h2></div><button type="button" className="admin-secondary-button" onClick={() => void validate(values)}><Info /> Refresh preview</button></div>{preview ? <><div className="admin-validation-metrics"><span>Total weight <strong>{preview.total_weight}</strong></span><span>Theoretical return <strong>{preview.theoretical_return_percent.toFixed(2)}%</strong></span><span>Status <strong>{preview.valid ? "Ready" : "Blocked"}</strong></span></div><div className="admin-validation-options">{preview.options.map((option) => <span key={option.code}><b>{option.code}</b>{option.probability_percent.toFixed(2)}% probability · {option.payout_contribution_percent.toFixed(2)}% return</span>)}</div>{preview.failures.length > 0 && <ul className="admin-validation-failures">{preview.failures.map((failure) => <li key={`${failure.field}-${failure.message}`}>{failure.field}: {failure.message}</li>)}</ul>}</> : <p className="admin-muted-copy">Run the preview before saving to inspect normalized probabilities and payout contribution.</p>}</section>
    <div className="admin-sticky-actions"><button type="button" className="admin-secondary-button" onClick={() => void validate(values)}><CheckCircle2 /> Validate</button><button className="admin-primary-button" disabled={isSubmitting || uploading !== null}>{isSubmitting ? <Loader2 className="admin-spin" /> : <Save />}{isSubmitting ? "Saving…" : submitLabel}</button></div>
  </form>;
}
