"use client";

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Copy, Loader2, Pause, Play, Plus, RefreshCw, Rocket, Save, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { ConfigEditor, newConfigDefaults } from "@/components/admin/config-editor";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { adminClient } from "@/lib/admin-client";
import type { AdminApproval, AdminConfigVersion, CreateAdminConfigInput } from "@/types/admin";
import { useAdminIdentity } from "@/components/admin/admin-gate";

function configInput(config: AdminConfigVersion): CreateAdminConfigInput {
  return { betting_duration_ms: config.betting_duration_ms, lock_duration_ms: config.lock_duration_ms, drawing_duration_ms: config.drawing_duration_ms, result_duration_ms: config.result_duration_ms, min_bet: config.min_bet, max_single_bet: config.max_single_bet, max_round_bet: config.max_round_bet, notes: config.notes || "", options: config.options.map(({ code, name, image_url, asset_id, display_order, payout_numerator, payout_denominator, probability_weight, is_enabled }) => ({ code, name, image_url, asset_id, display_order, payout_numerator, payout_denominator, probability_weight, is_enabled })), chip_values: config.chip_values.map(({ amount, display_order, is_enabled }) => ({ amount, display_order, is_enabled })) };
}

function statusVariant(status: string): "success" | "warning" | "secondary" | "outline" { if (status === "published" || status === "running") return "success"; if (status === "draft" || status === "paused" || status === "review_pending") return "warning"; return "secondary"; }

export function GreedyAdminPanel() {
  const identity = useAdminIdentity();
  const queryClient = useQueryClient();
  const [editor, setEditor] = useState<{ mode: "create"; initial: CreateAdminConfigInput } | { mode: "edit"; config: AdminConfigVersion } | null>(null);
  const [publishTarget, setPublishTarget] = useState<AdminConfigVersion | null>(null);
  const runtime = useQuery({ queryKey: ["admin", "greedy", "runtime"], queryFn: adminClient.runtime, refetchInterval: 5000 });
  const configs = useQuery({ queryKey: ["admin", "greedy", "configs"], queryFn: adminClient.configs });
  const approvals = useQuery({ queryKey: ["admin", "approvals", "greedy"], queryFn: () => adminClient.approvalsPaged("?page=1&limit=100"), refetchInterval: 8000 });
  const canManage = identity.role === "super_admin" || identity.role === "game_operator";
  const greedyApprovals = useMemo(() => (approvals.data?.data || []).filter((item) => item.action_type === "greedy.config.publish"), [approvals.data]);

  async function refresh() { await Promise.all([queryClient.invalidateQueries({ queryKey: ["admin", "greedy"] }), queryClient.invalidateQueries({ queryKey: ["admin", "approvals"] })]); }
  const action = useMutation({ mutationFn: async (next: "resume" | "pause") => next === "resume" ? adminClient.resume() : adminClient.pause(), onSuccess: async (_data, next) => { toast.success(next === "resume" ? "Greedy resumed" : "Greedy paused safely"); await refresh(); }, onError: (reason) => toast.error(reason instanceof Error ? reason.message : "Runtime action failed") });
  const clone = useMutation({ mutationFn: adminClient.cloneConfig, onSuccess: async (data) => { toast.success("Configuration cloned as a new draft"); await refresh(); setEditor({ mode: "edit", config: data }); }, onError: (reason) => toast.error(reason instanceof Error ? reason.message : "Clone failed") });
  const publish = useMutation({ mutationFn: (id: string) => adminClient.publish(id), onSuccess: async (data) => { const result = data as { approval_id?: string }; toast.success(result?.approval_id ? "Publish request submitted for approval" : "Configuration published"); setPublishTarget(null); await refresh(); }, onError: (reason) => toast.error(reason instanceof Error ? reason.message : "Publish request failed") });
  const decide = useMutation({ mutationFn: ({ approval, decision }: { approval: AdminApproval; decision: "approve" | "reject" }) => decision === "approve" ? adminClient.approve(approval.id, "Reviewed from Manage Greedy") : adminClient.reject(approval.id, "Rejected from Manage Greedy"), onSuccess: async (_data, variables) => { toast.success(`Publish request ${variables.decision}d`); await refresh(); }, onError: (reason) => toast.error(reason instanceof Error ? reason.message : "Approval action failed") });
  const applyApproved = useMutation({ mutationFn: adminClient.publishApproved, onSuccess: async () => { toast.success("Approved Greedy configuration is now live"); await refresh(); }, onError: (reason) => toast.error(reason instanceof Error ? reason.message : "Approved configuration could not be applied") });

  async function save(payload: CreateAdminConfigInput) {
    if (!editor) return;
    if (editor.mode === "create") await adminClient.createConfig(payload); else await adminClient.updateConfig(editor.config.id, payload);
    toast.success(editor.mode === "create" ? "Configuration draft created" : "Configuration draft updated");
    setEditor(null); await refresh();
  }

  if (runtime.isLoading || configs.isLoading) return <div className="grid min-h-64 place-items-center"><Loader2 className="size-6 animate-spin text-slate-400" /></div>;
  if (runtime.isError || configs.isError) return <Alert variant="destructive"><AlertTitle>Greedy administration is unavailable</AlertTitle><AlertDescription>{(runtime.error || configs.error as Error)?.message || "The backend could not be reached."}</AlertDescription></Alert>;

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="text-sm font-medium text-slate-500">Game administration</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Manage Greedy</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Control the runtime and publish versioned settings. The player snapshot automatically receives the newly published configuration.</p></div><Button variant="outline" onClick={() => void refresh()}><RefreshCw /> Refresh</Button></div>
    {!canManage && <Alert variant="warning"><ShieldCheck /><AlertTitle>Read-only access</AlertTitle><AlertDescription>Your admin role can inspect Greedy configuration but cannot change runtime or settings.</AlertDescription></Alert>}
    <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardDescription>Runtime status</CardDescription><CardTitle className="flex items-center gap-2 text-2xl"><Badge variant={statusVariant(runtime.data?.status || "unknown")}>{runtime.data?.status || "unknown"}</Badge></CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Active configuration</CardDescription><CardTitle className="text-2xl">{runtime.data?.active_config_version?.version ? `Version ${runtime.data.active_config_version.version}` : "Not published"}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Current round</CardDescription><CardTitle className="truncate text-base">{runtime.data?.current_round?.status?.replaceAll("_", " ") || "No active round"}</CardTitle></CardHeader></Card></div>
    <Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Runtime controls</CardTitle><CardDescription>Pause finishes the active round safely; resume starts/continues round creation.</CardDescription></div><div className="flex gap-2"><Button variant="outline" disabled={!canManage || action.isPending || runtime.data?.status !== "running"} onClick={() => action.mutate("pause")}><Pause /> Pause</Button><Button disabled={!canManage || action.isPending || runtime.data?.status === "running"} onClick={() => action.mutate("resume")}><Play /> Resume</Button></div></CardHeader></Card>
    <Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Configuration versions</CardTitle><CardDescription>Create, edit, clone and publish complete Greedy configurations.</CardDescription></div><Button disabled={!canManage} onClick={() => setEditor({ mode: "create", initial: newConfigDefaults })}><Plus /> New configuration</Button></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Version</TableHead><TableHead>Status</TableHead><TableHead>Timing</TableHead><TableHead>Bet limits</TableHead><TableHead>Options / chips</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{(configs.data || []).map((config) => <TableRow key={config.id}><TableCell className="font-semibold">v{config.version}</TableCell><TableCell><Badge variant={statusVariant(config.status)}>{config.status.replaceAll("_", " ")}</Badge></TableCell><TableCell className="text-slate-500">{config.betting_duration_ms / 1000}s bet · {config.drawing_duration_ms / 1000}s draw</TableCell><TableCell className="text-slate-500">{config.min_bet} – {config.max_round_bet}</TableCell><TableCell className="text-slate-500">{config.options.filter((item) => item.is_enabled).length} / {config.chip_values.filter((item) => item.is_enabled).length}</TableCell><TableCell><div className="flex justify-end gap-2">{config.status === "draft" && <Button size="sm" variant="outline" disabled={!canManage} onClick={() => setEditor({ mode: "edit", config })}><Save /> Edit</Button>}<Button size="sm" variant="outline" disabled={!canManage || clone.isPending} onClick={() => clone.mutate(config.id)}><Copy /> Clone</Button>{config.status === "draft" && <Button size="sm" disabled={!canManage || publish.isPending} onClick={() => setPublishTarget(config)}><Rocket /> Publish</Button>}</div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    {editor && <div className="space-y-4"><Separator /><div className="flex items-center justify-between"><div><h2 className="text-2xl font-semibold">{editor.mode === "create" ? "Create Greedy configuration" : `Edit version ${editor.config.version}`}</h2><p className="text-sm text-slate-500">Save as a draft, then submit it for approval and publication.</p></div><Button variant="outline" onClick={() => setEditor(null)}>Close editor</Button></div><ConfigEditor key={editor.mode === "create" ? "create" : editor.config.id} initial={editor.mode === "create" ? editor.initial : configInput(editor.config)} submitLabel={editor.mode === "create" ? "Create draft" : "Save draft"} onSave={save} /></div>}
    <Card><CardHeader><CardTitle>Greedy publish approvals</CardTitle><CardDescription>Publication requires review by another eligible administrator. The requester can apply an approved request from this page.</CardDescription></CardHeader><CardContent>{greedyApprovals.length ? <Table><TableHeader><TableRow><TableHead>Request</TableHead><TableHead>Status</TableHead><TableHead>Expires</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{greedyApprovals.map((approval) => { const requestedByMe = approval.requested_by_admin_id === identity.id; return <TableRow key={approval.id}><TableCell className="font-mono text-xs">{approval.id}</TableCell><TableCell><Badge variant={approval.status === "approved" ? "success" : approval.status === "pending" ? "warning" : "secondary"}>{approval.status}</Badge></TableCell><TableCell className="text-slate-500">{new Date(approval.expires_at).toLocaleString()}</TableCell><TableCell><div className="flex justify-end gap-2">{approval.status === "pending" && !requestedByMe && <><Button size="sm" variant="outline" disabled={decide.isPending} onClick={() => decide.mutate({ approval, decision: "reject" })}>Reject</Button><Button size="sm" disabled={decide.isPending} onClick={() => decide.mutate({ approval, decision: "approve" })}>Approve</Button></>}{approval.status === "approved" && requestedByMe && <Button size="sm" disabled={applyApproved.isPending} onClick={() => applyApproved.mutate(approval.id)}><Rocket /> Apply live</Button>}{approval.status === "pending" && requestedByMe && <span className="text-xs text-slate-500">Waiting for another admin</span>}</div></TableCell></TableRow>; })}</TableBody></Table> : <p className="text-sm text-slate-500">No Greedy publish approval requests are visible to this account.</p>}</CardContent></Card>
    <Dialog open={Boolean(publishTarget)} onOpenChange={(open) => { if (!open) setPublishTarget(null); }}><DialogContent><DialogHeader><DialogTitle>Publish configuration v{publishTarget?.version}</DialogTitle><DialogDescription>This submits the complete draft for independent approval. Once approved and applied, the Greedy user panel updates from its authoritative snapshot.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setPublishTarget(null)}>Cancel</Button><Button disabled={publish.isPending} onClick={() => publishTarget && publish.mutate(publishTarget.id)}>{publish.isPending ? <Loader2 className="animate-spin" /> : <Rocket />} Submit for approval</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
