"use client";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Clock3, Copy, GitCompare, LockKeyhole, Send, Upload } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { adminClient } from "@/lib/admin-client";
import type { AdminApproval, AdminConfigVersion, CreateAdminConfigInput } from "@/types/admin";
import { ConfigEditor } from "@/components/admin/config-editor";
import { ConfirmDialog, ErrorState, LoadingState, PageHeader, StatusPill } from "@/components/admin/admin-ui";

function editablePayload(config: AdminConfigVersion): CreateAdminConfigInput { return { betting_duration_ms: config.betting_duration_ms, lock_duration_ms: config.lock_duration_ms, drawing_duration_ms: config.drawing_duration_ms, result_duration_ms: config.result_duration_ms, min_bet: config.min_bet, max_single_bet: config.max_single_bet, max_round_bet: config.max_round_bet, notes: config.notes || "", options: config.options.map((item) => ({ ...item })), chip_values: config.chip_values.map((item) => ({ ...item })) }; }
const compareFields: Array<[keyof AdminConfigVersion, string]> = [["betting_duration_ms", "Betting duration"], ["lock_duration_ms", "Lock duration"], ["drawing_duration_ms", "Drawing duration"], ["result_duration_ms", "Result duration"], ["min_bet", "Minimum bet"], ["max_single_bet", "Single bet max"], ["max_round_bet", "Round bet max"]];

export default function ConfigDetailPage() {
  const { configId } = useParams<{ configId: string }>(); const router = useRouter(); const cache = useQueryClient(); const [compareId, setCompareId] = useState(""); const [notice, setNotice] = useState("");
  const configQuery = useQuery({ queryKey: ["admin", "config", configId], queryFn: () => adminClient.config(configId) });
  const configsQuery = useQuery({ queryKey: ["admin", "configs"], queryFn: adminClient.configs });
  const approvalsQuery = useQuery({ queryKey: ["admin", "approvals"], queryFn: () => adminClient.approvals() });
  const clone = useMutation({ mutationFn: () => adminClient.cloneConfig(configId), onSuccess: (draft) => { void cache.invalidateQueries({ queryKey: ["admin", "configs"] }); router.push(`/admin/greedy/configs/${draft.id}`); } });
  const requestPublish = useMutation({ mutationFn: () => adminClient.publish(configId), onSuccess: async () => { setNotice("Publish approval requested. A distinct eligible administrator must approve it before you can apply the version."); await Promise.all([configQuery.refetch(), approvalsQuery.refetch(), configsQuery.refetch()]); } });
  const approvals = (approvalsQuery.data || []) as AdminApproval[]; const approval = approvals.find((item) => item.action_type === "greedy.config.publish" && item.target_id === configId && !["rejected", "expired", "applied"].includes(item.status));
  const apply = useMutation({ mutationFn: () => { if (!approval) throw new Error("Approved request not found"); return adminClient.publishApproved(approval.id); }, onSuccess: async () => { setNotice("Approved configuration published for future rounds."); await Promise.all([configQuery.refetch(), approvalsQuery.refetch(), configsQuery.refetch()]); } });
  if (configQuery.isLoading) return <LoadingState />; if (configQuery.isError || !configQuery.data) return <ErrorState message={(configQuery.error as Error)?.message || "Configuration not found"} />;
  const config = configQuery.data; const compare = configsQuery.data?.find((item) => item.id === compareId);
  return <><PageHeader eyebrow="Greedy / configuration" title={`Version ${config.version}`} description={config.notes || "Review, compare, clone, edit, and move this version through approval."} action={<div className="admin-button-row"><Link href="/admin/greedy/configs" className="admin-secondary-button"><ArrowLeft /> Versions</Link><button className="admin-secondary-button" disabled={clone.isPending} onClick={() => clone.mutate()}><Copy /> Clone as draft</button></div>} />
    {notice && <div className="admin-form-success" role="status"><CheckCircle2 />{notice}</div>}
    <section className="admin-control-strip"><div><span className="admin-eyebrow">Lifecycle</span><strong><StatusPill status={config.status} /></strong></div><div><span className="admin-eyebrow">Approval</span><strong>{approval ? <StatusPill status={approval.status} /> : "No active request"}</strong></div><div className="admin-control-actions">{config.status === "draft" && <ConfirmDialog trigger={<button className="admin-primary-button"><Send /> Submit for approval</button>} title={`Submit version ${config.version} for approval?`} description="This does not publish the game. A distinct eligible administrator must approve the immutable snapshot before the requester can apply it." confirmLabel="Request approval" onConfirm={() => requestPublish.mutateAsync()} />}{config.status === "review_pending" && approval?.status === "approved" && <ConfirmDialog trigger={<button className="admin-primary-button"><Upload /> Apply approved version</button>} title="Apply the approved configuration?" description="Only the administrator who requested this approval can apply it. The current round remains on its frozen version; future rounds use this one." confirmLabel="Publish for future rounds" onConfirm={() => apply.mutateAsync()} />}{config.status !== "draft" && config.status !== "review_pending" && <span className="admin-readonly"><LockKeyhole /> Immutable version</span>}</div></section>
    {config.status === "draft" ? <ConfigEditor key={config.updated_at} initial={editablePayload(config)} submitLabel="Save draft changes" onSave={async (payload) => { await adminClient.updateConfig(config.id, payload); setNotice("Draft changes saved and validated."); await Promise.all([configQuery.refetch(), configsQuery.refetch()]); }} /> : <><section className="admin-stat-row"><div><Clock3 /><span>Betting</span><strong>{config.betting_duration_ms / 1000}s</strong></div><div><Clock3 /><span>Lock</span><strong>{config.lock_duration_ms}ms</strong></div><div><Clock3 /><span>Drawing</span><strong>{config.drawing_duration_ms / 1000}s</strong></div><div><Clock3 /><span>Result</span><strong>{config.result_duration_ms / 1000}s</strong></div></section><article className="admin-panel"><div className="admin-panel__top"><div><span className="admin-eyebrow">Outcome matrix</span><h2>{config.options.filter((item) => item.is_enabled).length} enabled options</h2></div></div><div className="admin-option-grid">{config.options.map((option) => <div className={`admin-option-card ${option.is_enabled ? "" : "is-off"}`} key={option.code}><div className="admin-option-card__art">{option.image_url ? <img src={option.image_url} alt="" /> : option.code[0]}</div><strong>{option.name}</strong><small>{option.code}</small><div><span>{option.payout_denominator === "1" ? `${option.payout_numerator}x` : `${option.payout_numerator}/${option.payout_denominator}x`} payout</span><span>{option.probability_weight} weight</span></div></div>)}</div></article></>}
    <article className="admin-panel admin-compare-panel"><div className="admin-panel__top"><div><span className="admin-eyebrow">Version comparison</span><h2>Compare configuration</h2></div><GitCompare /></div><label className="admin-compare-select">Compare against<select value={compareId} onChange={(event) => setCompareId(event.target.value)}><option value="">Choose a version</option>{configsQuery.data?.filter((item) => item.id !== config.id).map((item) => <option key={item.id} value={item.id}>Version {item.version} · {item.status}</option>)}</select></label>{compare && <div className="admin-compare-grid"><strong>Field</strong><strong>Version {config.version}</strong><strong>Version {compare.version}</strong>{compareFields.map(([key, label]) => <div className="admin-compare-row" key={key}><span>{label}</span><b>{String(config[key])}</b><b className={config[key] !== compare[key] ? "is-different" : ""}>{String(compare[key])}</b></div>)}</div>}</article>
  </>;
}
